apiVersion: v1
kind: Namespace
metadata:
  name: item-service-ns
  labels:
    app.kubernetes.io/name: item-service
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/enforce-version: "latest"
    # #This tells it to  monitor but not to block baseline policy violations
    pod-security.kubernetes.io/warn: "baseline"
    pod-security.kubernetes.io/warn-version: "latest"
    # #This tells it to audit restricted-level violations (for logs & compliance)
    pod-security.kubernetes.io/audit: "restricted"
    pod-security.kubernetes.io/audit-version: "latest"
