apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: item-service
  name: item-service-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: item-service-binding
  namespace: item-service
subjects:
  - kind: ServiceAccount
    name: item-service-sa
    namespace: item-service
roleRef:
  kind: Role
  name: item-service-role
  apiGroup: rbac.authorization.k8s.io
