apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: item-service-hpa
  namespace: item-service-ns
  labels:
    app: item-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: item-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
