apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: item-service-network-policy
spec:
  podSelector:
    matchLabels:
      app: item-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: nginx-ingress-controller
      ports:
        - protocol: TCP
          port: 8000
          #Example
          # - namespaceSelector:
          #     matchLabels:
          #       kubernetes.io/metadata.name: kube-system
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
          ports:
            - protocol: TCP
              port: 53
            - protocol: UDP
              port: 53

# Example: Allow egress only to other pods in the same namespace with specific labels
# - to:
#   - podSelector:
#       matchLabels:
#         app: database-service # If your app needs to talk to a database within the cluster
#   ports:
#   - protocol: TCP
#     port: 5432 # Database port
